language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href /vargas-deezer/

deploy:
  provider: pages
  skip_cleanup: true
  before_script:
    - npm install -g angular-cli-ghpages
  script:
    - npm ngh --dir=dist/vargas-deezer
  github_token: $GITHUB_TOKEN
  env:
    - GH_TOKEN=$GITHUB_TOKEN
  local_dir: dist/vargas-deezer
  on:
    branches: 
      - develop
      - github-page