language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- npm run e2e
- ng build --prod --base-href /vargas-deezer/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/vargas-deezer
  on:
    branch: develop